Repository watercrawl/WaterCrawl, pull requests merged in 2025-04, with the labels that each got.

#16 docs(docker): improve docker setup and documentation
  README.md
  backend/.env.example
  backend/.env.local
  backend/poetry.lock
  backend/pyproject.toml
  backend/watercrawl/settings.py
  docker/.env.example
  docker/docker-compose.yml
  frontend/src/cookie-consent/components/CookieConsentBanner.tsx
Labels: size:M

#17 chore: Enable MinIO consistency check on startup
  backend/.env.example
Labels: size:XS

#18 fix(security): update dependencies to address multiple vulnerabilities
  backend/poetry.lock
  backend/pyproject.toml
  docs/package.json
  docs/pnpm-lock.yaml
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: size:M

#19 fix: use gettext instead of gettext_lazy to fix error
  backend/common/docs.py
Labels: 🛠️ bug:backend, size:XS

#20 fix: update redoc package to use latest version
  docs/package.json
  docs/pnpm-lock.yaml
Labels: size:XS

#22 feat(docker): improve deployment infrastructure with Nginx and environment management
  CHANGELOG.md
  CONTRIBUTING.md
  DEPLOYMENT.md
  README.md
  backend/.env.example
  backend/.env.local
  backend/Readme.md
  docker/.env.example
  docker/.env.local
  docker/README.md
  docker/db.env
  docker/docker-compose.local.yml
  docker/docker-compose.yml
  docker/minio.env
  docker/nginx/default.conf
  docker/playwright.env
  docs/CHANGELOG.md
  frontend/LICENSE
  frontend/README.md
Labels: size:XXL

#23 docs: update CONTRIBUTING.md with correct file paths and commands
  CONTRIBUTING.md
Labels: size:M

#24 feat(docker): implement dynamic Nginx configuration for MinIO buckets
  DEPLOYMENT.md
  README.md
  docker/.env.example
  docker/.env.local
  docker/docker-compose.yml
  docker/nginx/entrypoint.sh
  docker/nginx/nginx.conf
Labels: size:M

#25 fix(docs): resolve API documentation rendering exception
  backend/common/docs.py
Labels: size:XS

#28 fix: fix build issue
  frontend/src/components/activity-logs/ActivityLogResultCard.tsx
  frontend/src/components/sitemap/SitemapGraphViewer.tsx
  frontend/src/types/crawl.ts
Labels: size:L

#29 ci(github): merge backend, frontend, and docs Docker build workflows into unified docker-publish.yml
  .github/workflows/docker-backend-publish.yml
  .github/workflows/docker-docs-publish.yml
  .github/workflows/docker-frontend-publish.yml
  .github/workflows/docker-publish.yml
Labels: 🧠 feat:workflow, size:L

#30 ci(github): add manual version bump and release PR workflow
  .github/workflows/manual-version-bump.yml
Labels: size:M

#31 chore: minor fixes
  .github/workflows/docker-publish.yml
Labels: size:M

#32 security: fix audit issues
  docs/pnpm-lock.yaml
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: size:XS

#33 fix: remove doc auto-build
  .github/workflows/docker-docs-manual.yml
  .github/workflows/docker-publish.yml
Labels: size:L

#35 Release v0.6.0
  DEPLOYMENT.md
  backend/pyproject.toml
  docker/.env.example
  docker/docker-compose.yml
  frontend/src/contexts/SettingsProvider.tsx
Labels: size:S

#36 flare, langchain, watercrawl tutorial added
  tutorials/FLARE-WaterCrawl-LangChain.ipynb
Labels: documentation, size:L

#37 stock analysis tutorial
  tutorials/Claude-3.7-WaterCrawl-stock-analyzer/Claude-3.7-&-WaterCrawl-stock-analyzer.py
  tutorials/Claude-3.7-WaterCrawl-stock-analyzer/Stock_Analyzer_Claude-3.7_WaterCrawl.ipynb
Labels: documentation, size:XL

#48 feat(search): replace scraping with Google Custom Search API
  backend/common/serializers.py
  backend/common/services.py
  backend/core/serializers.py
  backend/core/services.py
  backend/core/views.py
  backend/spider/settings.py
  backend/spider/spiders/google_search.py
  backend/watercrawl/settings.py
  frontend/src/contexts/SettingsProvider.tsx
  frontend/src/layouts/DashboardLayout.tsx
  frontend/src/pages/dashboard/SearchPage.tsx
  frontend/src/types/settings.ts
Labels: size:L

#49 feat(search): replace scraping with Google Custom Search API
  docker/.env.example
Labels: size:XS

#51 chore(release): bump version to v0.7.0
  DEPLOYMENT.md
  backend/pyproject.toml
  docker/.env.example
  docker/docker-compose.yml
Labels: size:S

#52 fix(search): credit calculation and validation
  CHANGELOG.md
  backend/plan/services.py
  backend/plan/validators.py
  frontend/src/components/search/SearchForm.tsx
  frontend/src/pages/dashboard/SearchPage.tsx
Labels: 🛠️ bug:backend, size:M

#53 Release v0.7.1
  DEPLOYMENT.md
  backend/pyproject.toml
  docker/.env.example
  docker/docker-compose.yml
Labels: size:S

#55 docs(api): add comprehensive search API documentation
  docs/docs/api/cancel-search.md
  docs/docs/api/create-search.md
  docs/docs/api/get-search.md
  docs/docs/api/monitor-search.md
  docs/docs/api/overview.md
  docs/docs/clients/go.md
  docs/docs/clients/nodejs.md
  docs/docs/clients/php.md
  docs/docs/clients/python.md
  docs/docs/self-hosted/configuration.md
  docs/docs/self-hosted/installation.md
  docs/docs/self-hosted/overview.md
  docs/docs/self-hosted/services.md
  docs/docs/self-hosted/troubleshooting.md
  docs/sidebars.ts
Labels: documentation, size:XXL
