Repository watercrawl/WaterCrawl, pull requests merged in 2025-05, with the labels that each got.

#61 feat(proxy): Implement proxy server management and integration
  backend/common/encryption.py
  backend/core/admin.py
  backend/core/consts.py
  backend/core/docs.py
  backend/core/migrations/0010_proxyserver.py
  backend/core/migrations/0011_alter_proxyserver_options_alter_proxyserver_password.py
  backend/core/migrations/0012_proxyserver_category.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/services.py
  backend/core/urls.py
  backend/core/views.py
  backend/plan/services.py
  backend/plan/validators.py
  backend/spider/middlewares.py
  backend/spider/spiders/scraper.py
  backend/watercrawl/settings.py
  frontend/src/components/crawl/CrawlForm.tsx
  frontend/src/components/forms/SpiderOptionsForm.tsx
  frontend/src/components/search/SearchForm.tsx
  frontend/src/components/search/SearchFormExample.tsx
  frontend/src/components/settings/ProxyForm.tsx
  frontend/src/components/settings/ProxyList.tsx
  frontend/src/components/settings/ProxySettings.tsx
  frontend/src/components/shared/ComboboxComponent.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useIsTabletOrMobile.ts
  frontend/src/pages/dashboard/SettingsPage.tsx
  frontend/src/services/api/proxy.ts
  frontend/src/types/crawl.ts
  frontend/src/types/proxy.ts
  frontend/src/utils/formatters.ts
Labels: ⚙️ feat:settings, 🖼️ feat:ui, 🔗 feat:integration, size:XXL

#63 docs(proxy): update proxy documentation
  DEPLOYMENT.md
  backend/.env.example
  docker/.env.example
  docker/docker-compose.yml
  docs/docs/self-hosted/configuration.md
  docs/docs/self-hosted/installation.md
  frontend/src/components/search/SearchFormExample.tsx
Labels: size:M

#64 feat: upgrade outdated dependencies
  backend/poetry.lock
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: size:M

#65 feat: upgrade outdated dependencies
  backend/poetry.lock
  backend/pyproject.toml
Labels: size:XS

#67 refactor(ui): improve settings loading experience
  frontend/src/App.tsx
  frontend/src/contexts/SettingsProvider.tsx
  frontend/src/layouts/AuthLayout.tsx
  frontend/src/layouts/DashboardLayout.tsx
  frontend/src/layouts/PublicSkeleton.tsx
  frontend/src/pages/auth/InstallPage.tsx
  frontend/src/pages/custom/ErrorPage.tsx
  frontend/src/pages/custom/InstallPage.tsx
  frontend/src/pages/custom/LoadingPage.tsx
Labels: ⚙️ feat:settings, 🖼️ feat:ui, 🏠 edition:self-hosted, size:L

#46 feat: Update Docker configuration for backend plugins
  .github/workflows/manual-version-bump.yml
  docker/backend/Dockerfile
  docker/backend/extra_requirements.txt
  docker/docker-compose.yml
Labels: 🔌 feat:plugin, size:M

#62 Updating the tutorials adding a new webpage crawl and chat tutorial
  tutorials/Claude-3.7-&-WaterCrawl-stock-analyzer/Claude-3.7-&-WaterCrawl-stock-analyzer.py
  tutorials/Claude-3.7-&-WaterCrawl-stock-analyzer/Stock_Analyzer_Claude-3.7_WaterCrawl.ipynb
  tutorials/Claude-3.7-&-WaterCrawl-stock-analyzer/blog.md
  tutorials/Claude-3.7-WaterCrawl-stock-analyzer/Claude-3.7-&-WaterCrawl-stock-analyzer.py
  tutorials/Claude-3.7-WaterCrawl-stock-analyzer/Stock_Analyzer_Claude-3.7_WaterCrawl.ipynb
  tutorials/DeepSeekR1_WaterCrawl_live_chat_with_your_website/DeepSeekR1_WaterCrawl_live_chat_with_your_webpage.py
  tutorials/DeepSeekR1_WaterCrawl_live_chat_with_your_website/DeepSeek_WaterCrawl_LiveChat_Tutorial.ipynb
  tutorials/DeepSeekR1_WaterCrawl_live_chat_with_your_website/blog.md
  tutorials/FLARE-WaterCrawl-LangChain/FLARE-WaterCrawl-LangChain.ipynb
  tutorials/FLARE-WaterCrawl-LangChain/FLARE-WaterCrawl-LangChain.py
  tutorials/FLARE-WaterCrawl-LangChain/blog.md
Labels: documentation, size:XXL

#68 chore(release): bump version to v0.8.0
  CHANGELOG.md
  DEPLOYMENT.md
  backend/pyproject.toml
  docker/.env.example
  docker/backend/Dockerfile
  docker/docker-compose.yml
Labels: size:M
